name: Sync Submodule (Test)

on:
  repository_dispatch:
    types:
      - sync_submodule

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update submodule
        run: |
          git submodule sync
          git submodule update --recursive --remote

      - name: Commit and push changes
        run: |
          git config user.name "muram-105"
          git config user.email "muram8700@gmail.com"
          git commit -am "Sync submodule"
          git push
