name: Update Common Submodule

on:
  push:
    branches:
      - '16.0'

jobs:
  update_test_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Test submodule
        run: |
          # Determine the path of the Common submodule in the Test repository
          COMMON_SUBMODULE_PATH=$(find . -type d -name "Common" | head -n 1)

          # Change to the Common submodule directory
          cd $GITHUB_WORKSPACE/$COMMON_SUBMODULE_PATH

          # Update the submodule
          git checkout main
          git pull origin main

          # Commit and push the submodule update
          git config --global user.email "muram8700@gmail.com"
          git config --global user.name "muram-105"

          git add .
          git commit -m "Update Common submodule" --no-verify
          git push origin main
