name: Sync Submodule

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update submodule
        env:
          PAT_TOKEN: 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
        run: |
          git submodule update --init --recursive
          git submodule update --remote
          git config user.email "muram8700@gmail.com"
          git config user.name "muram-105"
          git commit -am "Update submodule from common repository"
          git push
