name: Update Common Submodule

on:
  repository_dispatch:
    types:
      - update-test-submodule

jobs:
  update_common_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Common submodule
        run: |
          COMMON_SUBMODULE_PATH=$(find . -type d -name "Common" | head -n 1)
          cd $GITHUB_WORKSPACE/$COMMON_SUBMODULE_PATH
          git checkout main
          git pull origin main
          git add .
          git commit -m "Update Common submodule" --no-verify
          git push origin main
