name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    env:
      ENV_SECRET: ${{ secrets.TEST_REPO_TOKEN }}
    steps:
      - name: Step using Environment Secret
        run: echo "$ENV_SECRET"
